### ISSUE TITLE
App crashes after a few seconds after launch on Android

### ISSUE THREAD

**Issue by dnaicker86** [animo/paradym-wallet#53]
I am using Windows 11, command line, node version 18,

The initial launch of the app runs but after viewing the popup that says the various features of interaction and selecting home, it crashes with the following report:

```
 Logs for your project will appear below. Press Ctrl+C to exit.
Android Bundling complete 23246ms
 WARN  WARN: The '@aries-framework/askar' module is experimental and could have unexpected breaking changes. When using this module, make sure to use strict versions for all @aries-framework packages.
Error: ENOENT: no such file or directory, open 'C:\root\react-native\ReactAndroid\hermes-engine\.cxx\Release\2q6r403w\x86_64\lib\InternalBytecode\InternalBytecode.js'
    at Object.openSync (node:fs:601:3)
    at Object.readFileSync (node:fs:469:35)
    at getCodeFrame (C:\Users\denai\Github\Hyperledger_Aries\paradym-wallet\node_modules\metro\src\Server.js:975:18)
    at Server._symbolicate (C:\Users\denai\Github\Hyperledger_Aries\paradym-wallet\node_modules\metro\src\Server.js:1044:22)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Server._processRequest (C:\Users\denai\Github\Hyperledger_Aries\paradym-wallet\node_modules\metro\src\Server.js:417:7) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'C:\\root\\react-native\\ReactAndroid\\hermes-engine\\.cxx\\Release\\2q6r403w\\x86_64\\lib\\InternalBytecode\\InternalBytecode.js'
}
Error: ENOENT: no such file or directory, open 'C:\root\react-native\ReactAndroid\hermes-engine\.cxx\Release\2q6r403w\x86_64\lib\InternalBytecode\InternalBytecode.js'
    at Object.openSync (node:fs:601:3)
    at Object.readFileSync (node:fs:469:35)
    at getCodeFrame (C:\Users\denai\Github\Hyperledger_Aries\paradym-wallet\node_modules\metro\src\Server.js:975:18)
    at Server._symbolicate (C:\Users\denai\Github\Hyperledger_Aries\paradym-wallet\node_modules\metro\src\Server.js:1044:22)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Server._processRequest (C:\Users\denai\Github\Hyperledger_Aries\paradym-wallet\node_modules\metro\src\Server.js:417:7) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'C:\\root\\react-native\\ReactAndroid\\hermes-engine\\.cxx\\Release\\2q6r403w\\x86_64\\lib\\InternalBytecode\\InternalBytecode.js'
}
Error: ENOENT: no such file or directory, open 'C:\root\react-native\ReactAndroid\hermes-engine\.cxx\Release\2q6r403w\x86_64\lib\InternalBytecode\InternalBytecode.js'
    at Object.openSync (node:fs:601:3)
    at Object.readFileSync (node:fs:469:35)
    at getCodeFrame (C:\Users\denai\Github\Hyperledger_Aries\paradym-wallet\node_modules\metro\src\Server.js:975:18)
    at Server._symbolicate (C:\Users\denai\Github\Hyperledger_Aries\paradym-wallet\node_modules\metro\src\Server.js:1044:22)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Server._processRequest (C:\Users\denai\Github\Hyperledger_Aries\paradym-wallet\node_modules\metro\src\Server.js:417:7) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'C:\\root\\react-native\\ReactAndroid\\hermes-engine\\.cxx\\Release\\2q6r403w\\x86_64\\lib\\InternalBytecode\\InternalBytecode.js'
}
Error: ENOENT: no such file or directory, open 'C:\root\react-native\ReactAndroid\hermes-engine\.cxx\Release\2q6r403w\x86_64\lib\InternalBytecode\InternalBytecode.js'
    at Object.openSync (node:fs:601:3)
    at Object.readFileSync (node:fs:469:35)
    at getCodeFrame (C:\Users\denai\Github\Hyperledger_Aries\paradym-wallet\node_modules\metro\src\Server.js:975:18)
    at Server._symbolicate (C:\Users\denai\Github\Hyperledger_Aries\paradym-wallet\node_modules\metro\src\Server.js:1044:22)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Server._processRequest (C:\Users\denai\Github\Hyperledger_Aries\paradym-wallet\node_modules\metro\src\Server.js:417:7) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'C:\\root\\react-native\\ReactAndroid\\hermes-engine\\.cxx\\Release\\2q6r403w\\x86_64\\lib\\InternalBytecode\\InternalBytecode.js'
}
Error: ENOENT: no such file or directory, open 'C:\root\react-native\ReactAndroid\hermes-engine\.cxx\Release\2q6r403w\x86_64\lib\InternalBytecode\InternalBytecode.js'
    at Object.openSync (node:fs:601:3)
    at Object.readFileSync (node:fs:469:35)
    at getCodeFrame (C:\Users\denai\Github\Hyperledger_Aries\paradym-wallet\node_modules\metro\src\Server.js:975:18)
    at Server._symbolicate (C:\Users\denai\Github\Hyperledger_Aries\paradym-wallet\node_modules\metro\src\Server.js:1044:22)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Server._processRequest (C:\Users\denai\Github\Hyperledger_Aries\paradym-wallet\node_modules\metro\src\Server.js:417:7) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'C:\\root\\react-native\\ReactAndroid\\hermes-engine\\.cxx\\Release\\2q6r403w\\x86_64\\lib\\InternalBytecode\\InternalBytecode.js'
}
 WARN  WARN: The '@aries-framework/openid4vc-client' module is experimental and could have unexpected breaking changes. When using this module, make sure to use strict versions for all @aries-framework packages.
Error: ENOENT: no such file or directory, open 'C:\root\react-native\ReactAndroid\hermes-engine\.cxx\Release\2q6r403w\x86_64\lib\InternalBytecode\InternalBytecode.js'
    at Object.openSync (node:fs:601:3)
    at Object.readFileSync (node:fs:469:35)
    at getCodeFrame (C:\Users\denai\Github\Hyperledger_Aries\paradym-wallet\node_modules\metro\src\Server.js:975:18)
    at Server._symbolicate (C:\Users\denai\Github\Hyperledger_Aries\paradym-wallet\node_modules\metro\src\Server.js:1044:22)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Server._processRequest (C:\Users\denai\Github\Hyperledger_Aries\paradym-wallet\node_modules\metro\src\Server.js:417:7) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'C:\\root\\react-native\\ReactAndroid\\hermes-engine\\.cxx\\Release\\2q6r403w\\x86_64\\lib\\InternalBytecode\\InternalBytecode.js'
}
Error: ENOENT: no such file or directory, open 'C:\root\react-native\ReactAndroid\hermes-engine\.cxx\Release\2q6r403w\x86_64\lib\InternalBytecode\InternalBytecode.js'
    at Object.openSync (node:fs:601:3)
    at Object.readFileSync (node:fs:469:35)
    at getCodeFrame (C:\Users\denai\Github\Hyperledger_Aries\paradym-wallet\node_modules\metro\src\Server.js:975:18)
    at Server._symbolicate (C:\Users\denai\Github\Hyperledger_Aries\paradym-wallet\node_modules\metro\src\Server.js:1044:22)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Server._processRequest (C:\Users\denai\Github\Hyperledger_Aries\paradym-wallet\node_modules\metro\src\Server.js:417:7) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'C:\\root\\react-native\\ReactAndroid\\hermes-engine\\.cxx\\Release\\2q6r403w\\x86_64\\lib\\InternalBytecode\\InternalBytecode.js'
}
Error: ENOENT: no such file or directory, open 'C:\root\react-native\ReactAndroid\hermes-engine\.cxx\Release\2q6r403w\x86_64\lib\InternalBytecode\InternalBytecode.js'
    at Object.openSync (node:fs:601:3)
    at Object.readFileSync (node:fs:469:35)
    at getCodeFrame (C:\Users\denai\Github\Hyperledger_Aries\paradym-wallet\node_modules\metro\src\Server.js:975:18)
    at Server._symbolicate (C:\Users\denai\Github\Hyperledger_Aries\paradym-wallet\node_modules\metro\src\Server.js:1044:22)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Server._processRequest (C:\Users\denai\Github\Hyperledger_Aries\paradym-wallet\node_modules\metro\src\Server.js:417:7) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'C:\\root\\react-native\\ReactAndroid\\hermes-engine\\.cxx\\Release\\2q6r403w\\x86_64\\lib\\InternalBytecode\\InternalBytecode.js'
}
Error: ENOENT: no such file or directory, open 'C:\root\react-native\ReactAndroid\hermes-engine\.cxx\Release\2q6r403w\x86_64\lib\InternalBytecode\InternalBytecode.js'
    at Object.openSync (node:fs:601:3)
    at Object.readFileSync (node:fs:469:35)
    at getCodeFrame (C:\Users\denai\Github\Hyperledger_Aries\paradym-wallet\node_modules\metro\src\Server.js:975:18)
    at Server._symbolicate (C:\Users\denai\Github\Hyperledger_Aries\paradym-wallet\node_modules\metro\src\Server.js:1044:22)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Server._processRequest (C:\Users\denai\Github\Hyperledger_Aries\paradym-wallet\node_modules\metro\src\Server.js:417:7) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'C:\\root\\react-native\\ReactAndroid\\hermes-engine\\.cxx\\Release\\2q6r403w\\x86_64\\lib\\InternalBytecode\\InternalBytecode.js'
}
Error: ENOENT: no such file or directory, open 'C:\root\react-native\ReactAndroid\hermes-engine\.cxx\Release\2q6r403w\x86_64\lib\InternalBytecode\InternalBytecode.js'
    at Object.openSync (node:fs:601:3)
    at Object.readFileSync (node:fs:469:35)
    at getCodeFrame (C:\Users\denai\Github\Hyperledger_Aries\paradym-wallet\node_modules\metro\src\Server.js:975:18)
    at Server._symbolicate (C:\Users\denai\Github\Hyperledger_Aries\paradym-wallet\node_modules\metro\src\Server.js:1044:22)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Server._processRequest (C:\Users\denai\Github\Hyperledger_Aries\paradym-wallet\node_modules\metro\src\Server.js:417:7) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'C:\\root\\react-native\\ReactAndroid\\hermes-engine\\.cxx\\Release\\2q6r403w\\x86_64\\lib\\InternalBytecode\\InternalBytecode.js'
}
 INFO  INFO: Creating agent with config {
  "agentConfig": {
    "label": "Paradym Wallet",
    "walletConfig": {
      "id": "paradym-wallet-secure",
      "key": "[*****]",
      "storage": {}
    },
    "autoUpdateStorageOnStartup": true,
    "logger": 2,
    "agentDependencies": true
  }
}
 INFO  INFO: Initializing wallet 'paradym-wallet-secure' {
  "id": "paradym-wallet-secure",
  "key": "[*****]",
  "storage": {}
}
Error: ENOENT: no such file or directory, open 'C:\root\react-native\ReactAndroid\hermes-engine\.cxx\Release\2q6r403w\x86_64\lib\InternalBytecode\InternalBytecode.js'
    at Object.openSync (node:fs:601:3)
    at Object.readFileSync (node:fs:469:35)
    at getCodeFrame (C:\Users\denai\Github\Hyperledger_Aries\paradym-wallet\node_modules\metro\src\Server.js:975:18)
    at Server._symbolicate (C:\Users\denai\Github\Hyperledger_Aries\paradym-wallet\node_modules\metro\src\Server.js:1044:22)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Server._processRequest (C:\Users\denai\Github\Hyperledger_Aries\paradym-wallet\node_modules\metro\src\Server.js:417:7) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'C:\\root\\react-native\\ReactAndroid\\hermes-engine\\.cxx\\Release\\2q6r403w\\x86_64\\lib\\InternalBytecode\\InternalBytecode.js'
}
Error: ENOENT: no such file or directory, open 'C:\root\react-native\ReactAndroid\hermes-engine\.cxx\Release\2q6r403w\x86_64\lib\InternalBytecode\InternalBytecode.js'
    at Object.openSync (node:fs:601:3)
    at Object.readFileSync (node:fs:469:35)
    at getCodeFrame (C:\Users\denai\Github\Hyperledger_Aries\paradym-wallet\node_modules\metro\src\Server.js:975:18)
    at Server._symbolicate (C:\Users\denai\Github\Hyperledger_Aries\paradym-wallet\node_modules\metro\src\Server.js:1044:22)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Server._processRequest (C:\Users\denai\Github\Hyperledger_Aries\paradym-wallet\node_modules\metro\src\Server.js:417:7) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'C:\\root\\react-native\\ReactAndroid\\hermes-engine\\.cxx\\Release\\2q6r403w\\x86_64\\lib\\InternalBytecode\\InternalBytecode.js'
}
Error: ENOENT: no such file or directory, open 'C:\root\react-native\ReactAndroid\hermes-engine\.cxx\Release\2q6r403w\x86_64\lib\InternalBytecode\InternalBytecode.js'
    at Object.openSync (node:fs:601:3)
    at Object.readFileSync (node:fs:469:35)
    at getCodeFrame (C:\Users\denai\Github\Hyperledger_Aries\paradym-wallet\node_modules\metro\src\Server.js:975:18)
    at Server._symbolicate (C:\Users\denai\Github\Hyperledger_Aries\paradym-wallet\node_modules\metro\src\Server.js:1044:22)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Server._processRequest (C:\Users\denai\Github\Hyperledger_Aries\paradym-wallet\node_modules\metro\src\Server.js:417:7) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'C:\\root\\react-native\\ReactAndroid\\hermes-engine\\.cxx\\Release\\2q6r403w\\x86_64\\lib\\InternalBytecode\\InternalBytecode.js'
}
Error: ENOENT: no such file or directory, open 'C:\root\react-native\ReactAndroid\hermes-engine\.cxx\Release\2q6r403w\x86_64\lib\InternalBytecode\InternalBytecode.js'
    at Object.openSync (node:fs:601:3)
    at Object.readFileSync (node:fs:469:35)
    at getCodeFrame (C:\Users\denai\Github\Hyperledger_Aries\paradym-wallet\node_modules\metro\src\Server.js:975:18)
    at Server._symbolicate (C:\Users\denai\Github\Hyperledger_Aries\paradym-wallet\node_modules\metro\src\Server.js:1044:22)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Server._processRequest (C:\Users\denai\Github\Hyperledger_Aries\paradym-wallet\node_modules\metro\src\Server.js:417:7) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'C:\\root\\react-native\\ReactAndroid\\hermes-engine\\.cxx\\Release\\2q6r403w\\x86_64\\lib\\InternalBytecode\\InternalBytecode.js'
}
Error: ENOENT: no such file or directory, open 'C:\root\react-native\ReactAndroid\hermes-engine\.cxx\Release\2q6r403w\x86_64\lib\InternalBytecode\InternalBytecode.js'
    at Object.openSync (node:fs:601:3)
    at Object.readFileSync (node:fs:469:35)
    at getCodeFrame (C:\Users\denai\Github\Hyperledger_Aries\paradym-wallet\node_modules\metro\src\Server.js:975:18)
    at Server._symbolicate (C:\Users\denai\Github\Hyperledger_Aries\paradym-wallet\node_modules\metro\src\Server.js:1044:22)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Server._processRequest (C:\Users\denai\Github\Hyperledger_Aries\paradym-wallet\node_modules\metro\src\Server.js:417:7) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'C:\\root\\react-native\\ReactAndroid\\hermes-engine\\.cxx\\Release\\2q6r403w\\x86_64\\lib\\InternalBytecode\\InternalBytecode.js'
}
 WARN  Possible Unhandled Promise Rejection (id: 0):
TypeError: undefined is not a function
TypeError: undefined is not a function
    at anonymous (http://192.168.0.123:8081/index.bundle?platform=android&dev=true&minify=false&app=id.paradym.wallet.dev&modulesOnly=false&runModule=true:624211:23)
    at tryCallOne (/root/react-native/ReactAndroid/hermes-engine/.cxx/Release/2q6r403w/x86_64/lib/InternalBytecode/InternalBytecode.js:53:16)
    at anonymous (/root/react-native/ReactAndroid/hermes-engine/.cxx/Release/2q6r403w/x86_64/lib/InternalBytecode/InternalBytecode.js:139:27)
    at apply (native)
    at anonymous (http://192.168.0.123:8081/index.bundle?platform=android&dev=true&minify=false&app=id.paradym.wallet.dev&modulesOnly=false&runModule=true:29321:26)
    at _callTimer (http://192.168.0.123:8081/index.bundle?platform=android&dev=true&minify=false&app=id.paradym.wallet.dev&modulesOnly=false&runModule=true:29240:17)
    at _callReactNativeMicrotasksPass (http://192.168.0.123:8081/index.bundle?platform=android&dev=true&minify=false&app=id.paradym.wallet.dev&modulesOnly=false&runModule=true:29270:17)
    at callReactNativeMicrotasks (http://192.168.0.123:8081/index.bundle?platform=android&dev=true&minify=false&app=id.paradym.wallet.dev&modulesOnly=false&runModule=true:29433:44)
    at __callReactNativeMicrotasks (http://192.168.0.123:8081/index.bundle?platform=android&dev=true&minify=false&app=id.paradym.wallet.dev&modulesOnly=false&runModule=true:2579:46)
    at anonymous (http://192.168.0.123:8081/index.bundle?platform=android&dev=true&minify=false&app=id.paradym.wallet.dev&modulesOnly=false&runModule=true:2391:45)
    at __guard (http://192.168.0.123:8081/index.bundle?platform=android&dev=true&minify=false&app=id.paradym.wallet.dev&modulesOnly=false&runModule=true:2563:15)
    at flushedQueue (http://192.168.0.123:8081/index.bundle?platform=android&dev=true&minify=false&app=id.paradym.wallet.dev&modulesOnly=false&runModule=true:2390:21)
Error: ENOENT: no such file or directory, open 'C:\root\react-native\ReactAndroid\hermes-engine\.cxx\Release\2q6r403w\x86_64\lib\InternalBytecode\InternalBytecode.js'
    at Object.openSync (node:fs:601:3)
    at Object.readFileSync (node:fs:469:35)
    at getCodeFrame (C:\Users\denai\Github\Hyperledger_Aries\paradym-wallet\node_modules\metro\src\Server.js:975:18)
    at Server._symbolicate (C:\Users\denai\Github\Hyperledger_Aries\paradym-wallet\node_modules\metro\src\Server.js:1044:22)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Server._processRequest (C:\Users\denai\Github\Hyperledger_Aries\paradym-wallet\node_modules\metro\src\Server.js:417:7) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'C:\\root\\react-native\\ReactAndroid\\hermes-engine\\.cxx\\Release\\2q6r403w\\x86_64\\lib\\InternalBytecode\\InternalBytecode.js'
}
Error: ENOENT: no such file or directory, open 'C:\root\react-native\ReactAndroid\hermes-engine\.cxx\Release\2q6r403w\x86_64\lib\InternalBytecode\InternalBytecode.js'
    at Object.openSync (node:fs:601:3)
    at Object.readFileSync (node:fs:469:35)
    at getCodeFrame (C:\Users\denai\Github\Hyperledger_Aries\paradym-wallet\node_modules\metro\src\Server.js:975:18)
    at Server._symbolicate (C:\Users\denai\Github\Hyperledger_Aries\paradym-wallet\node_modules\metro\src\Server.js:1044:22)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Server._processRequest (C:\Users\denai\Github\Hyperledger_Aries\paradym-wallet\node_modules\metro\src\Server.js:417:7) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'C:\\root\\react-native\\ReactAndroid\\hermes-engine\\.cxx\\Release\\2q6r403w\\x86_64\\lib\\InternalBytecode\\InternalBytecode.js'
}
Error: ENOENT: no such file or directory, open 'C:\root\react-native\ReactAndroid\hermes-engine\.cxx\Release\2q6r403w\x86_64\lib\InternalBytecode\InternalBytecode.js'
    at Object.openSync (node:fs:601:3)
    at Object.readFileSync (node:fs:469:35)
    at getCodeFrame (C:\Users\denai\Github\Hyperledger_Aries\paradym-wallet\node_modules\metro\src\Server.js:975:18)
    at Server._symbolicate (C:\Users\denai\Github\Hyperledger_Aries\paradym-wallet\node_modules\metro\src\Server.js:1044:22)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Server._processRequest (C:\Users\denai\Github\Hyperledger_Aries\paradym-wallet\node_modules\metro\src\Server.js:417:7) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'C:\\root\\react-native\\ReactAndroid\\hermes-engine\\.cxx\\Release\\2q6r403w\\x86_64\\lib\\InternalBytecode\\InternalBytecode.js'
}
```

Currently it just shows a blank screen:
<img width="1768" alt="image" src="https://github.com/animo/paradym-wallet/assets/130728803/ba54de93-850a-4e50-93c7-d9cbe5ab00c7">

**Comment by berendsliedrecht** [comment]
really old issue, likely fixed during updates of dependencies.
